/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.38                          *
*        Compiled Nov 24 2016, 16:57:40                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <string.h>
#include "AppDisplay.h"
#include "PE_Types.h"
#include "Global_data.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END
static float r = 108;
static float SinTable[60];

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
char *itoa_re(int num, char *str, int radix, int strlength);

static void DrawCircle(void)
{
    int x, y;
    GUI_SetBkColor(GUI_BLACK);
    GUI_SetColor(GUI_WHITE);
    GUI_DrawCircle(SCREEN_XSIZE/2, SCREEN_YSIZE/2, (SCREEN_YSIZE - 10)/2);
    GUI_DrawCircle(SCREEN_XSIZE/2, SCREEN_YSIZE/2, (SCREEN_YSIZE - 10)/2 + 1);
    GUI_DrawCircle(SCREEN_XSIZE/2, SCREEN_YSIZE/2, (SCREEN_YSIZE - 10)/2 + 2);

    for(uint8 i = 0; i < 60; i++)
    {
      x = (int)(r * SinTable[(i + 15)%60]);
      y = (int)(r * SinTable[i]);
      if((i % 15) == 0)
      {
        GUI_SetColor(GUI_GREEN);
        GUI_FillCircle(SCREEN_XSIZE/2 + x, SCREEN_YSIZE/2 + y, 4);
      }
      else if((i % 5) == 0)
      {
        GUI_SetColor(GUI_GREEN);
        GUI_FillCircle(SCREEN_XSIZE/2 + x, SCREEN_YSIZE/2 + y, 2);
      }
      else
      {
        GUI_SetColor(GUI_GRAY);
        GUI_FillCircle(SCREEN_XSIZE/2 + x, SCREEN_YSIZE/2 + y, 1);
      }	
    }
}

static void DrawLine(void)
{
    int x, y;
    float r;
    uint32 second_cnt;
    uint8 clock_second, clock_minute, clock_hour, daycnt;
    char num_display[12], num_transfer[3];

    second_cnt = TotalTimeSeconds;
    clock_second = (uint8)(second_cnt % 60);
    clock_minute = (uint8)((second_cnt / 60) % 60);
    clock_hour   = (uint8)(((second_cnt / 60) / 60) % 24);
    daycnt = (uint8)(second_cnt / 86400);

    // second
    GUI_SetPenSize(1);
    GUI_SetColor(GUI_GRAY);
    r = SCREEN_YSIZE/2 - 20;
    x = SCREEN_XSIZE/2 + (int)(r * SinTable[clock_second]);
    y = SCREEN_YSIZE/2 - (int)(r * SinTable[(clock_second + 15)%60]);
    GUI_DrawLine(SCREEN_XSIZE/2, SCREEN_YSIZE/2, x, y);

    // minute
    GUI_SetPenSize(3);
    GUI_SetColor(GUI_BLUE);
    r = SCREEN_YSIZE/2 - 30;
    x = SCREEN_XSIZE/2 + (int)(r * SinTable[clock_minute]);
    y = SCREEN_YSIZE/2 - (int)(r * SinTable[(clock_minute + 15)%60]);			
    GUI_DrawLine(SCREEN_XSIZE/2, SCREEN_YSIZE/2, x, y);

    // Hour
    GUI_SetPenSize(3);
    GUI_SetColor(GUI_GREEN);
    r = SCREEN_YSIZE/2 - 40;
    x = SCREEN_XSIZE/2 + (int)(r * SinTable[(clock_hour % 12) * 5 + clock_minute/12]);
    y = SCREEN_YSIZE/2 - (int)(r * SinTable[(((clock_hour % 12) * 5 + clock_minute/12 + 15) % 60)]);			
    GUI_DrawLine(SCREEN_XSIZE/2, SCREEN_YSIZE/2, x, y);

    memset(num_display, 0, 12);
    // day
    itoa_re(daycnt, num_transfer, 10, 2);
    strncpy(num_display, num_transfer, 2);
    strcat(num_display, ":");
    // hour
    itoa_re(clock_hour, num_transfer, 10, 2);
    strncpy(num_display + 3, num_transfer, 2);
    strcat(num_display, ":");
    // minute
    itoa_re(clock_minute, num_transfer, 10, 2);
    strncpy(num_display + 6, num_transfer, 2);
    strcat(num_display, ":");
    // second
    itoa_re(clock_second, num_transfer, 10, 2);
    strncpy(num_display + 9, num_transfer, 2);	

    GUI_SetColor(GUI_WHITE);	
    GUI_DispStringAt(num_display, (SCREEN_XSIZE - GUI_GetStringDistX(num_display))/2, SCREEN_YSIZE/2 + 16);	
}

// USER START (Optionally insert additional static code)
// USER END


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN hItem;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId) {
      case WM_INIT_DIALOG:
          //
          // Initialization of 'Window'
          //
          hItem = pMsg->hWin;
          WINDOW_SetBkColor(hItem, GUI_BLACK);
          // USER START (Optionally insert additional code for further widget initialization)
          // USER END
          for(uint8 i = 0; i < 60; i++)
          {
            SinTable[i] = (float)sin(PI * i / 30);
          }
          break;
      // USER START (Optionally insert additional message handling)
      // USER END
      case WM_PAINT:
          GUI_MULTIBUF_BeginEx(0);
          GUI_Clear();
          DrawCircle();
          DrawLine();
          GUI_MULTIBUF_EndEx(0);
          break;
    
      case USER_MESSAGE_1:
          break;
      
    default:
      WM_DefaultProc(pMsg);
      break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

char *itoa_re(int num, char *str, int radix, int strlength)
{
    char* ptr = str;
	char* ptemp;
    int i;
    int j;
	int orilen;
	if(num == 0)
	{
		for(i = 0; i < strlength; i++)
			str[i] = '0';
		return str;
	}
    while (num)
    {
        *ptr++  = num % radix + '0';
        num    /= radix;
        if (num < radix)
        {
            *ptr++  = num + '0';
            *ptr    = '\0';
            break;
        }
    }
    j = ptr - str - 1;
    for (i = 0; i < (ptr - str) / 2; i++)
    {
        int temp = str[i];
        str[i]  = str[j];
        str[j--] = temp;
    }

	orilen = strlen(str);
	if(orilen < strlength)
	{
		strcpy(ptemp, str);
		for(i = 0; i < (strlength - orilen); i++)
			str[i] = '0';
		strcat(str + i, ptemp);
		str[strlength] = '\0';
	}

    return str;
}


/*************************** End of file ****************************/
