/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : DMACH1.c
**     Project     : PE_Test
**     Processor   : MK70FN1M0VMJ15
**     Component   : DMAChannel_LDD
**     Version     : Component 01.051, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-09-02, 16:27, # CodeGen: 159
**     Abstract    :
**          This embedded component implements
**          a DMA transfer channel descriptor definition.
**     Settings    :
**          Component name                                 : DMACH1
**          Hardware request                               : Disabled
**          Channel select                                 : Fixed
**            DMA controller device                        : DMA1
**            Channel                                      : DMA_Channel0
**            Allocate channel                             : yes
**            Arbitration type                             : Fixed
**              Priority                                   : 0
**            Interrupt service                            : Enabled
**              Transfer complete interrupt                : 
**                Interrupt vector                         : INT_DMA0_DMA16
**                Interrupt priority                       : 8
**              Error interrupt                            : 
**                Interrupt vector                         : INT_DMA_Error
**                Interrupt priority                       : medium priority
**          External object declaration                    : (string list)
**          Source transaction settings                    : 
**            Start address                                : 0
**            Transaction size                             : 32-bits
**            Address adjustment                           : 0
**            Address modulo                               : Buffer disabled
**          Destination transaction settings               : 
**            Start address                                : 0
**            Transaction size                             : 32-bits
**            Address adjustment                           : 0
**            Address modulo                               : Buffer disabled
**          Transfer settings                              : 
**            Bandwidth control                            : No stalls
**            Transaction size                             : 32-bits
**            Transactions count                           : 1
**            Request count                                : 1
**            After request complete actions               : 
**              Channel linking                            : Disabled
**              Address adjustment                         : Disabled
**            After transfer complete actions              : 
**              Disable peripheral request                 : no
**              Channel linking                            : Disabled
**              Address adjustment                         : Disabled
**              Scatter/gather                             : Disabled
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Half complete                                : Disabled
**            Event mask                                   : 
**              OnComplete                                 : Enabled
**              OnError                                    : Enabled
**     Contents    :
**         Init                          - LDD_TDeviceData* DMACH1_Init(LDD_TUserData *UserDataPtr);
**         Enable                        - LDD_TError DMACH1_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable                       - LDD_TError DMACH1_Disable(LDD_TDeviceData *DeviceDataPtr);
**         StartTransfer                 - LDD_TError DMACH1_StartTransfer(LDD_TDeviceData *DeviceDataPtr);
**         GetTransferCompleteStatus     - bool DMACH1_GetTransferCompleteStatus(LDD_TDeviceData *DeviceDataPtr);
**         GetError                      - LDD_DMA_TErrorFlags DMACH1_GetError(LDD_TDeviceData *DeviceDataPtr);
**         SetSourceAddress              - LDD_TError DMACH1_SetSourceAddress(LDD_TDeviceData *DeviceDataPtr,...
**         SetSourceTransactionSize      - LDD_TError DMACH1_SetSourceTransactionSize(LDD_TDeviceData *DeviceDataPtr,...
**         SetDestinationAddress         - LDD_TError DMACH1_SetDestinationAddress(LDD_TDeviceData *DeviceDataPtr,...
**         SetDestinationTransactionSize - LDD_TError DMACH1_SetDestinationTransactionSize(LDD_TDeviceData...
**         SetTransactionCount           - LDD_TError DMACH1_SetTransactionCount(LDD_TDeviceData *DeviceDataPtr,...
**         SetRequestCount               - LDD_TError DMACH1_SetRequestCount(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file DMACH1.c
** @version 01.00
** @brief
**          This embedded component implements
**          a DMA transfer channel descriptor definition.
*/         
/*!
**  @addtogroup DMACH1_module DMACH1 module documentation
**  @{
*/         

/* MODULE DMACH1. */

#include "Events.h"
#include "DMACH1.h"
/* {Default RTOS Adapter} No RTOS includes */

#define DMACH1_INIT_EVENTS_MASK ((LDD_TEventMask)( \
          LDD_DMA_ON_COMPLETE | \
          LDD_DMA_ON_ERROR))

/* Channel configuration structure */
DMA1_TChnInit const DMACH1_ChInit = {
  /* Logical channel number */
  DMA1_STATIC_CHANNEL_0,               /* Phy channel: DMA_Channel0 */
  { /* TCD initial settings */
    DMA_SADDR_SADDR(0x00),             /* TCD_SADDR register initial value */
    DMA_SOFF_SOFF(0x00),               /* TCD_SOFF register initial value */
    ( DMA_ATTR_SMOD(0x00) |
      DMA_ATTR_SSIZE(0x02) |
      DMA_ATTR_DMOD(0x00) |
      DMA_ATTR_DSIZE(0x02)
    ),                                 /* TCD_ATTR register initial value */
    DMA_NBYTES_MLNO_NBYTES(0x04),      /* TCD_NBYTES_MLNO register initial value */
    DMA_SLAST_SLAST(0x00),             /* TCD_SLAST register initial value */
    DMA_DADDR_DADDR(0x00),             /* TCD_DADDR register initial value */
    DMA_DOFF_DOFF(0x00),               /* TCD_DOFF register initial value */
    (DMA_CITER_ELINKYES_LINKCH(0x00) | DMA_CITER_ELINKYES_CITER(0x01)), /* TCD_CITER_ELINKYES register initial value */
    DMA_DLAST_SGA_DLASTSGA(0x00),      /* TCD_DLASTSGA register initial value */
    (DMA_CSR_BWC(0x00) | DMA_CSR_MAJORLINKCH(0x00) | DMA_CSR_INTMAJOR_MASK), /* TCD_CSR register initial value */
    (DMA_BITER_ELINKYES_LINKCH(0x00) | DMA_BITER_ELINKYES_BITER(0x01)) /* TCD_BITER_ELINKYES register initial value */
  },
  /* DMAMUX initial settings */
  DMAMUX_CHCFG_SOURCE(0x00),           /* DMA multiplexor configuration register initial value 'SW request' */
  { /* Events initial setting */
    &DMACH1_OnComplete,                /* OnComplete callback address */
    &DMACH1_OnError                    /* OnComplete callback address */
  },
  TRUE                                 /* Channel state variable initial value */
};

/*
** ===================================================================
**     Method      :  DMACH1_Init (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Initializes the DMAChannel_LDD component. This method
**         allocates no memory. Memory for all DMA used channles is
**         allocated by DMAController componet .
**         This method can be called only once. Before the second call
**         of Init() the Deinit() must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Device data structure pointer.
*/
/* ===================================================================*/
LDD_TDeviceData* DMACH1_Init(LDD_TUserData *UserDataPtr)
{
  LDD_TDeviceData                 *DevDataPtr; /* DMA device data structure pointer */
  LDD_TDeviceData                 *ChnDevDataPtr; /* DMA channel device data structure pointer */

  DevDataPtr = PE_LDD_DeviceDataList[PE_LDD_COMPONENT_DMA1_ID]; /* Get DMA peripheral handle */
  if (DevDataPtr == NULL) {            /* Is DMA peripheral initialized? */
    DevDataPtr = DMA1_Init();          /* No, try to initialize it */
    if (DevDataPtr == NULL) {          /* initialization failed? */
      return NULL;                     /* Yes, return NULL */
    }
  }
  /* Initialize DMA channel device and get DMA channel handle */
  ChnDevDataPtr = DMA1_InitChannel(DevDataPtr, (DMA1_TChnInit *)(void *)&DMACH1_ChInit, UserDataPtr);
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_DMACH1_ID,ChnDevDataPtr);
  /* Return pointer to the channel data structure */
  return (ChnDevDataPtr);
}

/*
** ===================================================================
**     Method      :  DMACH1_Enable (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Enables the DMAChannel_LDD component.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK.
*/
/* ===================================================================*/
LDD_TError DMACH1_Enable(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_Enable((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  DMACH1_Disable (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Disables the DMAChannel_LDD component.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK.
*/
/* ===================================================================*/
LDD_TError DMACH1_Disable(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_Disable((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  DMACH1_StartTransfer (component DMAChannel_LDD)
*/
/*!
**     @brief
**         The method starts DMA transfer on the selected DMA channel.
**         This methods initiates explicit SW transfer request. Please
**         note that call of this method if peripheral request is
**         enabled can cause unpredictable behaviour.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled.
*/
/* ===================================================================*/
LDD_TError DMACH1_StartTransfer(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_StartTransfer((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  DMACH1_GetTransferCompleteStatus (component DMAChannel_LDD)
*/
/*!
**     @brief
**         This method returns value of "Transfer done" flag and clears
**         this flag if it was set. It is intended to be used in
**         pooling mode ([Interrupt service] = Disabled) to check
**         transfer state. Please note that in pooling mode the [Main()]
**         method must be called before this method is called.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Return values: 
**                           - [true] - Last transfer is done. 
**                           - [false] - Transfer is pending or last
**                           call of this method has returned [true].
*/
/* ===================================================================*/
bool DMACH1_GetTransferCompleteStatus(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_GetTransferCompleteStatus((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  DMACH1_GetError (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Returns channel error flags and clears these flags. 
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - DMA Error flags.
*/
/* ===================================================================*/
LDD_DMA_TErrorFlags DMACH1_GetError(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_GetError((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  DMACH1_SetSourceAddress (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets source(read) transaction address.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Address         - Data source address.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled. 
**                           - ERR_PARAM_ADDRESS - Source address is not
**                           multiple of DMA transaction size (byte,
**                           word, dword, ...)
*/
/* ===================================================================*/
LDD_TError DMACH1_SetSourceAddress(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TData *Address)
{
  return DMA1_SetSourceAddress((DMA1_TChanDeviceData *)DeviceDataPtr, Address);
}

/*
** ===================================================================
**     Method      :  DMACH1_SetDestinationAddress (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets destination(write) transaction address.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Address         - Data destination address.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled. 
**                           - ERR_PARAM_ADDRESS - Source address is not
**                           multiple of DMA transaction size (byte,
**                           word, dword, ...)
*/
/* ===================================================================*/
LDD_TError DMACH1_SetDestinationAddress(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TData *Address)
{
  return DMA1_SetDestinationAddress((DMA1_TChanDeviceData *)DeviceDataPtr, Address);
}

/*
** ===================================================================
**     Method      :  DMACH1_SetSourceTransactionSize (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets source transaction (DMA bus-read cycle) data size.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         TransactionSize - Source (bus-read)
**                           transaction data size in bytes.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled. 
**                           - ERR_PARAM_SIZE - Requested transfer size
**                           is not supported by selected DMA device.
*/
/* ===================================================================*/
LDD_TError DMACH1_SetSourceTransactionSize(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TTransactionSize TransactionSize)
{
  return DMA1_SetSourceTransactionSize((DMA1_TChanDeviceData *)DeviceDataPtr, TransactionSize);
}

/*
** ===================================================================
**     Method      :  DMACH1_SetDestinationTransactionSize (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets destination transaction (DMA bus-write cycle) data size.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         TransactionSize - Destination
**                           (bus-write) transaction data size in bytes.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled. 
**                           - ERR_PARAM_SIZE - Requested transfer size
**                           is not supported by selected DMA device.
*/
/* ===================================================================*/
LDD_TError DMACH1_SetDestinationTransactionSize(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TTransactionSize TransactionSize)
{
  return DMA1_SetDestinationTransactionSize((DMA1_TChanDeviceData *)DeviceDataPtr, TransactionSize);
}

/*
** ===================================================================
**     Method      :  DMACH1_SetTransactionCount (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets number of R/W transaction performed after next request
**         is asserted. Please note the this value doesn't represent
**         number of transferred bytes but number on R/W transaction
**         units.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         TransactionCount - Number of R/W
**                           transaction performed after next request is
**                           asserted.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled.
*/
/* ===================================================================*/
LDD_TError DMACH1_SetTransactionCount(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TTransactionCount TransactionCount)
{
  return DMA1_SetTransactionCount((DMA1_TChanDeviceData *)DeviceDataPtr, TransactionCount);
}

/*
** ===================================================================
**     Method      :  DMACH1_SetRequestCount (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets number of requests required to complete transfer.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         RequestCount    - Number of requests
**                           required to complete transfer.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled.
*/
/* ===================================================================*/
LDD_TError DMACH1_SetRequestCount(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TRequestCount RequestCount)
{
  return DMA1_SetRequestCount((DMA1_TChanDeviceData *)DeviceDataPtr, RequestCount);
}

/* END DMACH1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
