/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LCDC1.h
**     Project     : PE_Test
**     Processor   : MK70FN1M0VMJ15
**     Component   : LCDC_LDD
**     Version     : Component 01.025, Driver 01.02, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-08-30, 16:21, # CodeGen: 148
**     Abstract    :
**
**     Settings    :
**          Component name                                 : LCDC1
**          Device                                         : LCDC
**          Interrupt service                              : Enabled
**            Interrupt                                    : INT_LCD
**            Interrupt priority                           : medium priority
**            Plane 0 interrupt                            : End of frame
**            Plane 1 interrupt                            : End of frame
**            Interrupt event                              : First/last memory read
**          Panel type                                     : TFT
**            Bits per pixel                               : 24
**            Width in pixels                              : 320
**            Height in pixels                             : 240
**            Endian select                                : Big
**            Signal polarity                              : 
**              Pixel polarity                             : Active high
**              HSYNC polarity                             : Active low
**              VSYNC polarity                             : Active low
**              Output enable (OE) polarity                : Active high
**              Pixel clock polarity                       : Active high
**            Display timing                               : 
**              Pixel clock                                : 6 MHz
**              Pixel clock period                         :  166.667 ns
**              PixClk and OE during sync                  : Always on
**              Horizontal                                 : 
**                HSYNC pulse width                        : 2
**                HSYNC pulse width                        :  333.334 ns
**                Front porch width                        : 20
**                Front porch width                        :  3333.34 ns
**                Back porch width                         : 66
**                Back porch width                         :  11000.022 ns
**                Total line width                         : 408
**                Total line width                         :  68.00408 us
**              Vertical                                   : 
**                VSYNC pulse width                        : 1
**                VSYNC pulse width                        :  68.00408 us
**                Front porch width                        : 4
**                Front porch width                        :  272.01632 us
**                Back porch width                         : 18
**                Back porch width                         :  1224.07344 us
**              Contrast control                           : Disabled
**          Settings                                       : TFT
**            HW cursor initialization                     : Enabled
**              Arithmetic operation                       : Cursor disabled
**              X-position                                 : 0
**              Y-position                                 : 0
**              Cursor width                               : 0
**              Cursor height                              : 0
**              Blinking                                   : Disabled
**              Blinking rate                              : 1
**              Cursor blink frequency                     : 32 Hz (31 ms)
**              Cursor color                               : 
**                Red                                      : 0
**                Green                                    : 0
**                Blue                                     : 0
**            Plane 0 initialization                       : Enabled
**              External object declaration                : 
**              Address                                    : 0x80000000
**              Vertical scan direction                    : Normal
**              Width in pixels                            : 320
**              Height in pixels                           : 240
**              Window position X                          : 0
**              Window position Y                          : 0
**              Window width                               : 320
**              Window height                              : 240
**              Position on screen X                       : 0
**              Position on screen Y                       : 0
**            Plane 1 initialization                       : Disabled
**          Pins                                           : TFT, 24 bit bus
**            LCD Data Red[0]                              : Enabled
**              Red[0] pin                                 : PTF20/SPI2_PCS1/FTM2_CH0/UART5_TX/GLCD_D16
**              Red[0] pin signal                          : 
**            LCD Data Red[1]                              : Enabled
**              Red[1] pin                                 : ADC3_SE6b/PTF21/FTM2_CH1/UART5_RTS_b/GLCD_D17
**              Red[1] pin signal                          : 
**            LCD Data Red[2]                              : Enabled
**              Red[2] pin                                 : ADC3_SE7b/PTF22/I2C0_SCL/FTM1_CH0/UART5_CTS_b/GLCD_D18
**              Red[2] pin signal                          : 
**            LCD Data Red[3]                              : Enabled
**              Red[3] pin                                 : ADC3_SE10/PTF23/I2C0_SDA/FTM1_CH1/TRACE_CLKOUT/GLCD_D19
**              Red[3] pin signal                          : 
**            LCD Data Red[4]                              : Enabled
**              Red[4] pin                                 : ADC3_SE11/PTF24/CAN1_RX/FTM1_QD_PHA/TRACE_D3/GLCD_D20
**              Red[4] pin signal                          : 
**            LCD Data Red[5]                              : Enabled
**              Red[5] pin                                 : ADC3_SE12/PTF25/CAN1_TX/FTM1_QD_PHB/TRACE_D2/GLCD_D21
**              Red[5] pin signal                          : 
**            LCD Data Red[6]                              : Enabled
**              Red[6] pin                                 : ADC3_SE13/PTF26/FTM2_QD_PHA/TRACE_D1/GLCD_D22
**              Red[6] pin signal                          : 
**            LCD Data Red[7]                              : Enabled
**              Red[7] pin                                 : ADC3_SE14/PTF27/FTM2_QD_PHB/TRACE_D0/GLCD_D23
**              Red[7] pin signal                          : 
**            LCD Data Green[0]                            : Enabled
**              Green[0] pin                               : ADC2_SE16/PTE8/I2S0_RXD1/UART5_TX/I2S0_RX_FS/GLCD_D8/FTM3_CH3
**              Green[0] pin signal                        : 
**            LCD Data Green[1]                            : Enabled
**              Green[1] pin                               : ADC2_SE17/PTE9/I2S0_TXD1/UART5_RX/I2S0_RX_BCLK/GLCD_D9/FTM3_CH4
**              Green[1] pin signal                        : 
**            LCD Data Green[2]                            : Enabled
**              Green[2] pin                               : PTE10/UART5_CTS_b/I2S0_TXD0/GLCD_D10/FTM3_CH5
**              Green[2] pin signal                        : 
**            LCD Data Green[3]                            : Enabled
**              Green[3] pin                               : ADC3_SE16/PTE11/UART5_RTS_b/I2S0_TX_FS/GLCD_D11/FTM3_CH6
**              Green[3] pin signal                        : 
**            LCD Data Green[4]                            : Enabled
**              Green[4] pin                               : ADC3_SE17/PTE12/I2S0_TX_BCLK/GLCD_D12/FTM3_CH7
**              Green[4] pin signal                        : 
**            LCD Data Green[5]                            : Enabled
**              Green[5] pin                               : PTF17/SPI2_SCK/FTM0_CH4/UART0_RX/GLCD_D13
**              Green[5] pin signal                        : 
**            LCD Data Green[6]                            : Enabled
**              Green[6] pin                               : PTF18/SPI2_SOUT/FTM1_CH0/UART0_TX/GLCD_D14
**              Green[6] pin signal                        : 
**            LCD Data Green[7]                            : Enabled
**              Green[7] pin                               : PTF19/SPI2_SIN/FTM1_CH1/UART5_RX/GLCD_D15
**              Green[7] pin signal                        : 
**            LCD Data Blue[0]                             : Enabled
**              Blue[0] pin                                : ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/GLCD_D0/I2C1_SDA/RTC_CLKOUT
**              Blue[0] pin signal                         : 
**            LCD Data Blue[1]                             : Enabled
**              Blue[1] pin                                : ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/GLCD_D1/I2C1_SCL/SPI1_SIN
**              Blue[1] pin signal                         : 
**            LCD Data Blue[2]                             : Enabled
**              Blue[2] pin                                : ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/GLCD_D2
**              Blue[2] pin signal                         : 
**            LCD Data Blue[3]                             : Enabled
**              Blue[3] pin                                : ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/GLCD_D3/SPI1_SOUT
**              Blue[3] pin signal                         : 
**            LCD Data Blue[4]                             : Enabled
**              Blue[4] pin                                : PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/GLCD_D4
**              Blue[4] pin signal                         : 
**            LCD Data Blue[5]                             : Enabled
**              Blue[5] pin                                : PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/GLCD_D5/FTM3_CH0
**              Blue[5] pin signal                         : 
**            LCD Data Blue[6]                             : Enabled
**              Blue[6] pin                                : PTE6/SPI1_PCS3/UART3_CTS_b/I2S0_MCLK/GLCD_D6/FTM3_CH1/USB_SOF_OUT
**              Blue[6] pin signal                         : 
**            LCD Data Blue[7]                             : Enabled
**              Blue[7] pin                                : PTE7/UART3_RTS_b/I2S0_RXD0/GLCD_D7/FTM3_CH2
**              Blue[7] pin signal                         : 
**            Pixel clock pin                              : Enabled
**              Pixel clock pin                            : PTD12/SPI2_SCK/FTM3_FLT0/SDHC0_D4/FBa_A20/GLCD_PCLK
**              Pixel clock pin signal                     : 
**            VSYNC                                        : Enabled
**              VSYNC pin                                  : PTD15/SPI2_PCS1/SDHC0_D7/FBa_A23/GLCD_VFS
**              VSYNC pin signal                           : 
**            HSYNC                                        : Enabled
**              HSYNC pin                                  : PTD14/SPI2_SIN/SDHC0_D6/FBa_A22/GLCD_HFS
**              HSYNC pin signal                           : 
**            Output enable pin                            : Enabled
**              OE pin                                     : PTD13/SPI2_SOUT/SDHC0_D5/FBa_A21/GLCD_DE
**              OE pin signal                              : 
**            Contrast pin                                 : Enabled
**              Contrast pin                               : PTD11/SPI2_PCS0/UART5_CTS_b/SDHC0_CLKIN/FBa_A19/GLCD_CONTRAST
**              Constrast pin signal                       : 
**          DMA                                            : 
**            Layer 0                                      : 
**              Burst length                               : Dynamic
**              High mark                                  : 4
**              Trigger mark                               : 96
**            Layer 1                                      : 
**              Burst length                               : Dynamic
**              High mark                                  : 4
**              Trigger mark                               : 96
**          Initialization                                 : 
**            Enable module                                : yes
**            Start in self-refresh mode                   : no
**            Event mask                                   : 
**              OnError                                    : Disabled
**              OnEndOfFrame                               : Enabled
**              OnStartOfFrame                             : Disabled
**            Auto initialization                          : no
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init                   - LDD_TDeviceData* LCDC1_Init(LDD_TUserData *UserDataPtr);
**         SetupBitmap            - LDD_TError LCDC1_SetupBitmap(LDD_TDeviceData *DeviceDataPtr,...
**         SetupWindow            - LDD_TError LCDC1_SetupWindow(LDD_TDeviceData *DeviceDataPtr,...
**         SetupWindowPosOnScreen - LDD_TError LCDC1_SetupWindowPosOnScreen(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file LCDC1.h
** @version 01.02
** @brief
**
*/         
/*!
**  @addtogroup LCDC1_module LCDC1 module documentation
**  @{
*/         
#ifndef __LCDC1_H
#define __LCDC1_H

/* MODULE LCDC1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LCDC_PDD.h"
#include "PORT_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  LDD_TUserData *UserDataPtr;          /* Pointer to user data */
  uint8_t CursorOperation;             /* Cursor type */
  uint8_t BPP;                         /* Bits per pixel */
  bool ModuleEnabled;                  /* Module enabled */
  LDD_TData* L0Bitmap;                 /* Bitmap address for plane 0 */
  uint16_t L0BitmapVirtualWidth;       /* Bitmap virtual width for plane 0 */
  LDD_TData* L1Bitmap;                 /* Bitmap address for plane 1 */
  uint16_t L1BitmapVirtualWidth;       /* Bitmap virtual width for plane 1 */
  uint16_t InitState;                  /* Initialization flags */
  uint16_t L0BitmapHeightPx;           /* Bitmap height in pixels */
  uint16_t L1BitmapHeightPx;           /* Bitmap height in pixels */
  uint16_t L0BitmapWidthPx;            /* Bitmap width in pixels */
  uint16_t L0WindowWidthPx;            /* Window width in pixels */
  uint16_t L0WindowHeightPx;           /* Window height in pixels */
  uint16_t L1BitmapWidthPx;            /* Bitmap width in pixels */
  uint16_t L1WindowWidthPx;            /* Window width in pixels */
  uint16_t L1WindowHeightPx;           /* Window height in pixels */
} LCDC1_TDeviceData;

typedef LCDC1_TDeviceData *LCDC1_TDeviceDataPtr; /* Pointer to the device data structure. */

#define LCD_RES_X 320
#define LCD_RES_Y 240


/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define LCDC1_PRPH_BASE_ADDRESS  0x400B6000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define LCDC1_Init_METHOD_ENABLED      /*!< Init method of the component LCDC1 is enabled (generated) */
#define LCDC1_SetupBitmap_METHOD_ENABLED /*!< SetupBitmap method of the component LCDC1 is enabled (generated) */
#define LCDC1_SetupWindow_METHOD_ENABLED /*!< SetupWindow method of the component LCDC1 is enabled (generated) */
#define LCDC1_SetupWindowPosOnScreen_METHOD_ENABLED /*!< SetupWindowPosOnScreen method of the component LCDC1 is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define LCDC1_OnEndOfFrame_EVENT_ENABLED /*!< OnEndOfFrame event of the component LCDC1 is enabled (generated) */

/*
** ===================================================================
**     Method      :  LCDC1_Init (component LCDC_LDD)
*/
/*!
**     @brief
**         Initializes the device and allocates memory for the private
**         device data structure.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* LCDC1_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  LCDC1_Interrupt (component LCDC_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void LCDC1_Interrupt(void);

/*
** ===================================================================
**     Method      :  LCDC1_SetupBitmap (component LCDC_LDD)
*/
/*!
**     @brief
**         This method configures bitmap (virtual page) for selected
**         layer. 
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by Init method. 
**     @param
**         PlaneID         - Plane specification.
**     @param
**         BitmapInfo      - Pointer to bitmap
**                           information. 
**     @return
**                         - Error code: 
**                           ERR_OK - ok 
**                           ERR_PARAM_INDEX - plane not supported
*/
/* ===================================================================*/
LDD_TError LCDC1_SetupBitmap(LDD_TDeviceData *DeviceDataPtr, LDD_LCDC_TPlaneID PlaneID, LDD_LCDC_TBitmap *BitmapInfo);

/*
** ===================================================================
**     Method      :  LCDC1_SetupWindow (component LCDC_LDD)
*/
/*!
**     @brief
**         This method configures window in bitmap, that will be
**         displayed. 
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by Init method. 
**     @param
**         PlaneID         - Plane specification.
**     @param
**         WindowInfo      - Pointer to window information
**     @return
**                         - Error code: 
**                           ERR_OK - ok 
**                           ERR_PARAM_RANGE - window crosses bitmap
**                           boundary (range checking must be enabled) 
**                           ERR_PARAM_INDEX - plane not supported 
**                           ERR_FAILED - initialization error - call
**                           SetupBitmap() before SetupWindow() for
**                           selected plane
*/
/* ===================================================================*/
LDD_TError LCDC1_SetupWindow(LDD_TDeviceData *DeviceDataPtr, LDD_LCDC_TPlaneID PlaneID, LDD_LCDC_TWindow *WindowInfo);

/*
** ===================================================================
**     Method      :  LCDC1_SetupWindowPosOnScreen (component LCDC_LDD)
*/
/*!
**     @brief
**         This method configures window position on the screen.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by Init method. 
**     @param
**         PlaneID         - Plane specification.
**     @param
**         X               - Window position on the screen - X
**     @param
**         Y               - Window position on the screen - Y
**     @return
**                         - Error code: 
**                           ERR_OK - ok 
**                           ERR_PARAM_INDEX - plane not supported 
**                           ERR_PARAM_RANGE - window position is out of
**                           range (range checking optimalization must
**                           be enabled) 
**                           ERR_FAILED - initialization error - call
**                           SetupBitmap and SetupWindow before
**                           SetupWindowPosOnScreen()
*/
/* ===================================================================*/
LDD_TError LCDC1_SetupWindowPosOnScreen(LDD_TDeviceData *DeviceDataPtr, LDD_LCDC_TPlaneID PlaneID, uint16_t X, uint16_t Y);

/* END LCDC1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __LCDC1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
