/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : USB1.h
**     Project     : PE_Test
**     Processor   : MK70FN1M0VMJ15
**     Component   : USB_LDD
**     Version     : Component 01.307, Driver 01.09, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-09-24, 09:27, # CodeGen: 178
**     Abstract    :
**         This component implements an low level USB API.
**     Settings    :
**          Component name                                 : USB1
**          USB module (SIE)                               : USB0
**          Input clock frequency [MHz]                    : 48 MHz
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_USB0
**            Interrupt priority                           : medium priority
**          Mode                                           : HOST
**            Transceiver type                             : Internal
**              Transceiver module                         : USB0_FS
**              Transceiver weak pull-downs                : Enabled
**              USB revision                               : USB 2.0
**              Host data rates                            : 
**                Low speed                                : yes
**                Full speed                               : yes
**                High speed                               : no
**              Pin/signal setting                         : 
**                Clock pin                                : Disabled
**                USB data pins                            : 
**                  Data plus                              : 
**                    Pin                                  : USB0_DP
**                    Pin signal                           : 
**                  Data minus                             : 
**                    Pin                                  : USB0_DM
**                    Pin signal                           : 
**                VBUS pins                                : 
**                  VBUS enable                            : Disabled
**                  VBUS overcurrent                       : Disabled
**                Pullup/Pulldown pins                     : 
**                  DP pulldown                            : Enabled
**                    Pin                                  : USB0_Internal_DP_PD
**                    Pin signal                           : 
**                    Polarity                             : Activ high
**                  DM pulldown                            : Enabled
**                    Pin                                  : USB0_Internal_DM_PD
**                    Pin signal                           : 
**                    Polarity                             : Activ high
**            Host mode setting                            : 
**              Max. pipes                                 : 3
**              Max. transfers                             : 4
**              Asynchronous transfers                     : yes
**                Control transfers                        : yes
**                Bulk transfers                           : yes
**              Periodic transfers                         : no
**            Initialization                               : 
**              Enabled in init. code                      : no
**              Auto initialization                        : no
**              Event mask                                 : 
**                OnHostDeviceDeattach                     : Enabled
**                OnHostResetRecovery                      : Enabled
**                OnHostResumeRecovery                     : Enabled
**                OnHostError                              : Disabled
**                OnHost1msTimer                           : Disabled
**                OnSignalChange                           : Enabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init               - LDD_TDeviceData * USB1_Init(LDD_TUserData *UserDataPtr);
**         Enable             - LDD_TError USB1_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable            - LDD_TError USB1_Disable(LDD_TDeviceData *DeviceDataPtr);
**         HostGetPortState   - LDD_USB_Host_TState USB1_HostGetPortState(LDD_TDeviceData *DeviceDataPtr);
**         HostSetPortState   - LDD_TError USB1_HostSetPortState(LDD_TDeviceData *DeviceDataPtr,...
**         HostOpenPipe       - LDD_TError USB1_HostOpenPipe(LDD_TDeviceData *DeviceDataPtr,...
**         HostClosePipe      - LDD_TError USB1_HostClosePipe(LDD_TDeviceData *DeviceDataPtr,...
**         HostSendSetup      - LDD_TError USB1_HostSendSetup(LDD_TDeviceData *DeviceDataPtr,...
**         HostSendData       - LDD_TError USB1_HostSendData(LDD_TDeviceData *DeviceDataPtr,...
**         HostRecvData       - LDD_TError USB1_HostRecvData(LDD_TDeviceData *DeviceDataPtr,...
**         HostCancelTransfer - LDD_TError USB1_HostCancelTransfer(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file USB1.h
** @version 01.09
** @brief
**         This component implements an low level USB API.
*/         
/*!
**  @addtogroup USB1_module USB1 module documentation
**  @{
*/         

#ifndef __USB1_H
#define __USB1_H

/* MODULE USB1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define USB1_PRPH_BASE_ADDRESS  0x40072000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define USB1_Init_METHOD_ENABLED       /*!< Init method of the component USB1 is enabled (generated) */
#define USB1_Enable_METHOD_ENABLED     /*!< Enable method of the component USB1 is enabled (generated) */
#define USB1_Disable_METHOD_ENABLED    /*!< Disable method of the component USB1 is enabled (generated) */
#define USB1_HostGetPortState_METHOD_ENABLED /*!< HostGetPortState method of the component USB1 is enabled (generated) */
#define USB1_HostSetPortState_METHOD_ENABLED /*!< HostSetPortState method of the component USB1 is enabled (generated) */
#define USB1_HostOpenPipe_METHOD_ENABLED /*!< HostOpenPipe method of the component USB1 is enabled (generated) */
#define USB1_HostClosePipe_METHOD_ENABLED /*!< HostClosePipe method of the component USB1 is enabled (generated) */
#define USB1_HostSendSetup_METHOD_ENABLED /*!< HostSendSetup method of the component USB1 is enabled (generated) */
#define USB1_HostSendData_METHOD_ENABLED /*!< HostSendData method of the component USB1 is enabled (generated) */
#define USB1_HostRecvData_METHOD_ENABLED /*!< HostRecvData method of the component USB1 is enabled (generated) */
#define USB1_HostCancelTransfer_METHOD_ENABLED /*!< HostCancelTransfer method of the component USB1 is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define USB1_OnHostDeviceDeattach_EVENT_ENABLED /*!< OnHostDeviceDeattach event of the component USB1 is enabled (generated) */
#define USB1_OnHostResetRecovery_EVENT_ENABLED /*!< OnHostResetRecovery event of the component USB1 is enabled (generated) */
#define USB1_OnHostResumeRecovery_EVENT_ENABLED /*!< OnHostResumeRecovery event of the component USB1 is enabled (generated) */

/* Driver mode */
#define USB1_MODE_HOST

/*
** ===================================================================
**     Method      :  USB1_Init (component USB_LDD)
*/
/*!
**     @brief
**         Initializes USB device. Allocates memory for the device data
**         structure, interrupts, pins, etc. This method doesn't enable
**         device pull-up. Use Enable() method to enable device pull-up.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData * USB1_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  USB1_Enable (component USB_LDD)
*/
/*!
**     @brief
**         Enables the USB device (PHY, SIE). Enables device's DP(DM)
**         pull-up.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - 
*/
/* ===================================================================*/
LDD_TError USB1_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  USB1_Disable (component USB_LDD)
*/
/*!
**     @brief
**         Disabled device's DP(DM) pull-up. Disables PHY, etc.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - 
*/
/* ===================================================================*/
LDD_TError USB1_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  USB1_HostGetPortState (component USB_LDD)
*/
/*!
**     @brief
**         Returns port <state>.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Returned value:
**                           LDD_USB_HOST_DISABLED - Host mode is
**                           disabled (by the user or by the clock
**                           configuration).
**                           LDD_USB_HOST_DISABLED_BY_OTG - Host mode is
**                           disabled by the OTG driver.
**                           LDD_USB_HOST_PORT_POWERED_OFF - Port is
**                           powered-off.
**                           LDD_USB_HOST_PORT_DISCONNECTED -  No device
**                           is connected.
**                           LDD_USB_HOST_PORT_DISABLED - Device is
**                           connected to the port.
**                           LDD_USB_HOST_PORT_RESETING - Port generates
**                           reset signaling.
**                           LDD_USB_HOST_PORT_RESET_RECOVERING - Port
**                           waits 10 ms for reset recovery.
**                           LDD_USB_HOST_PORT_ENABLED - Device is
**                           connected, reset and ready to use.
**                           LDD_USB_HOST_PORT_SUSPENDED - Port is
**                           suspended.
**                           LDD_USB_HOST_PORT_RESUME_READY - Port is
**                           ready to generate resume signaling.
**                           LDD_USB_HOST_PORT_RESUMING - Port generates
**                           resume signaling.
**                           LDD_USB_HOST_PORT_RESUME_RECOVERING - Port
**                           waits 10 ms for resume recovery.
*/
/* ===================================================================*/
LDD_USB_Host_TState USB1_HostGetPortState(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  USB1_HostSetPortState (component USB_LDD)
*/
/*!
**     @brief
**         This method sets root port (bus) states. Supported commands
**         are:
**         [LDD_USB_HOST_PORT_CMD_POWER_OFF]
**         Deactivates VBUS enable signal and sets the port to the
**         POWER_OFF state, closes all pipes and discards all pending
**         transfers.
**         [LDD_USB_HOST_PORT_CMD_POWER_ON]
**         Activates VBUS enable signal and sets the port to the
**         DISCONNECTED state.
**         Port must be in the POWERED_OFF state to be power on.
**         [LDD_USB_HOST_PORT_CMD_RESET]
**         Sets the port to the RESETING state, starts the reset
**         signaling and closes all pipes and discards all pending
**         transfers. As soon as the reset interval is elapsed the
**         reset signaling will be stopped, the port state will be
**         change to the RESET_RECOVERING, and the reset recovery
**         interval will begin. After the reset recovery interval is
**         elapsed, the port state will be changed to the ENABLED state.
**         In the ENABLED state the port can used to transfer data.
**         Device must be connected (ports state > DISCONNECTED) before
**         reset can be started.
**         [LDD_USB_HOST_PORT_CMD_DISABLE]
**         Sets the port to the DISABLED state and closes all pipes and
**         discards all pending transfers. This state can be changed
**         only by performing the bus reset(transfer to the ENABLED
**         state), by disconnecting the device (transfer to the
**         DISCONNECT state) or by the powering-off the bus (transfer
**         to the POWERED_OFF state).
**         [LDD_USB_HOST_PORT_CMD_SUSPEND]
**         Suspends port (state = SUSPENDED). No transaction should be
**         pending before this method is called.
**         Port must be in the LDD_USB_HOST_PORT_ENABLED state to be
**         suspend.
**         [LDD_USB_HOST_PORT_CMD_RESUME]
**         Sets the port to the RESUMING state and starts the resume
**         signaling. After the resume interval is elapsed, the port
**         state will be changed to the ENABLED state. In the ENABLED
**         state the port can used to transfer data.
**         Port must be in the LDD_USB_HOST_PORT_RESUME_READY state
**         before resume can start.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Cmd             - Command
**     @return
**                         - Return value: ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration.
**                           ERR_DISABLED - The component is disabled.
**                           ERR_PARAM_COMMAND - Unknown command.
**                           ERR_USB_HOST_XXX where XXX is name of the
**                           state - Requested operation cannot be is
**                           done in current <state>.
*/
/* ===================================================================*/
LDD_TError USB1_HostSetPortState(LDD_TDeviceData *DeviceDataPtr, LDD_USB_Host_TPortControlCmd Cmd);

/*
** ===================================================================
**     Method      :  USB1_HostOpenPipe (component USB_LDD)
*/
/*!
**     @brief
**         Initializes pipe according to the values in the endpoint
**         descriptor and in the flags parameter. Allocate bandwidth
**         for periodic transfer types.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         PipeInitParamsPtr - Pointer to the
**                           structure containing pipe configuration
**                           data.
**     @param
**         PipeHandlePtr   - Pointer to pipe handle
**                           variable.
**     @return
**                         - Return value:
**                           ERR_DISABLED - Device is disabled.
**                           ERR_PARAM_ID - Requested transfer is not
**                           supported by the HW .
**                           ERR_OVERFLOW - Not enough frame time for
**                           periodic transfer type.
**                           ERR_OK - OK
*/
/* ===================================================================*/
LDD_TError USB1_HostOpenPipe(LDD_TDeviceData *DeviceDataPtr, LDD_USB_Host_TPipeDescr *PipeInitParamsPtr, LDD_USB_Host_TPipeHandle **PipeHandlePtr);

/*
** ===================================================================
**     Method      :  USB1_HostClosePipe (component USB_LDD)
*/
/*!
**     @brief
**         Deinitializes EP and disables it in the HW. For control EP
**         both directions are deinitialized. All pending transfers are
**         aborted and callback functions are called, if enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         PipeHandlePtr   - Pipe handle
**     @return
**                         - Return value:
**                           ERR_DISABLED - Device is disabled.
**                           ERR_OK - OK
*/
/* ===================================================================*/
LDD_TError USB1_HostClosePipe(LDD_TDeviceData *DeviceDataPtr, LDD_USB_Host_TPipeHandle *PipeHandlePtr);

/*
** ===================================================================
**     Method      :  USB1_HostSendSetup (component USB_LDD)
*/
/*!
**     @brief
**         This method prepares control transfer. All transfer phases
**         are handled by this method.
**         Note: On some MCUs (e.g. Kinetis) must be the address of the
**         data buffer 4 bytes aligned.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         PipeHandlePtr   - Pipe handle.
**     @param
**         TransferDescriptorPtr -
**                           Pointer to transfer descriptor.
**     @param
**         TransferHandlePtr - Pointer to
**                           transfer handle variable.
**     @return
**                         - Return value: ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration.
**                           ERR_DISABLED - The component is disabled.
**                           ERR_PARAM_ADDRESS - Transfer descriptor
**                           pointer or Pipe descriptor pointer is NULL.
**                           ERR_PARAM_DATA - Pointer to the Setup data
**                           packet is NULL.
**                           ERR_FAILED - Pipe is closed.
**                           ERR_USB_HOST_XXX where XXX is name of the
**                           state - Port is not in enabled <state>.
*/
/* ===================================================================*/
LDD_TError USB1_HostSendSetup(LDD_TDeviceData *DeviceDataPtr, LDD_USB_Host_TPipeHandle *PipeHandlePtr, LDD_USB_Host_TTD *TransferDescriptorPtr, LDD_USB_Host_TTransferHandle **TransferHandlePtr);

/*
** ===================================================================
**     Method      :  USB1_HostSendData (component USB_LDD)
*/
/*!
**     @brief
**         This method prepares data to be sent to the device.
**         Note: On some MCUs (e.g. Kinetis) must be the address of the
**         data buffer 4 bytes aligned.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         PipeHandlePtr   - Pipe handle.
**     @param
**         TransferDescriptorPtr -
**                           Pointer to transfer descriptor.
**     @param
**         TransferHandlePtr - Pointer to
**                           transfer handle variable.
**     @return
**                         - Return value: ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration.
**                           ERR_DISABLED - The component is disabled.
**                           ERR_PARAM_ADDRESS - Transfer descriptor
**                           pointer or Pipe handle is NULL.
**                           ERR_FAILED - Pipe is closed.
**                           ERR_USB_HOST_XXX where XXX is name of the
**                           state - Port is not in enabled <state>.
*/
/* ===================================================================*/
LDD_TError USB1_HostSendData(LDD_TDeviceData *DeviceDataPtr, LDD_USB_Host_TPipeHandle *PipeHandlePtr, LDD_USB_Host_TTD *TransferDescriptorPtr, LDD_USB_Host_TTransferHandle **TransferHandlePtr);

/*
** ===================================================================
**     Method      :  USB1_HostRecvData (component USB_LDD)
*/
/*!
**     @brief
**         This method prepares buffer for data sent by the device.
**         Note: On some MCUs (e.g. Kinetis) must be the address of the
**         data buffer 4 bytes aligned.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         PipeHandlePtr   - Pipe handle.
**     @param
**         TransferDescriptorPtr -
**                           Pointer to transfer descriptor.
**     @param
**         TransferHandlePtr - Pointer to
**                           transfer handle variable.
**     @return
**                         - Return value: ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration.
**                           ERR_DISABLED - The component is disabled.
**                           ERR_PARAM_ADDRESS - Transfer descriptor
**                           pointer or Pipe handle is NULL.
**                           ERR_FAILED - Pipe is closed.
**                           ERR_USB_HOST_XXX where XXX is name of the
**                           state - Port is not in enabled <state>.
*/
/* ===================================================================*/
LDD_TError USB1_HostRecvData(LDD_TDeviceData *DeviceDataPtr, LDD_USB_Host_TPipeHandle *PipeHandlePtr, LDD_USB_Host_TTD *TransferDescriptorPtr, LDD_USB_Host_TTransferHandle **TransferHandlePtr);

/*
** ===================================================================
**     Method      :  USB1_HostCancelTransfer (component USB_LDD)
*/
/*!
**     @brief
**         This method cancels all pending transfer requests in the
**         given EP queue. Callback function is called ( if enabled)
**         for each cancelled transfer request.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         PipeHandlePtr   - Pipe handle
**     @return
**                         - Return value: ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration.
**                           ERR_DISABLED - The component is disabled.
**                           ERR_PARAM_ADDRESS - Transfer descriptor
**                           pointer or Pipe handle is NULL.
**                           ERR_FAILED - Pipe is closed.
**                           ERR_USB_HOST_XXX where XXX is name of the
**                           state - Port is not in enabled <state>.
*/
/* ===================================================================*/
LDD_TError USB1_HostCancelTransfer(LDD_TDeviceData *DeviceDataPtr, LDD_USB_Host_TPipeDescr *PipeHandlePtr);

/*
** ===================================================================
**     Method      :  USB1_USB_Interrupt (component USB_LDD)
**
**     Description :
**         USB interrupt handler
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(USB1_USB_Interrupt);

/* END USB1. */

#endif
/* ifndef __USB1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
